trigger: none

pool:
  vmImage: windows-latest

variables:
  PACKAGES: $(Pipeline.Workspace)/.npm

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        echo '$(Build.SourcesDirectory)'
        cd $(Build.SourcesDirectory)
        ls -lrta
  - task: Cache@2
    displayName: 'Cache'
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
        npm
      path: '$(PACKAGES)'
      cacheHitVar: 'CACHE_RESTORED'
  - task: NodeTool@0
    displayName: 'Global - Tools - Install Node 8.9.1' #building
    enabled: true
    inputs:
      versionSpec: '8.9.1'
  - task: Npm@1
    displayName: 'Global - Tools - Install npm 6.4.1'
    enabled: true
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)'
      customCommand: 'i -g npm@6.4.1'

